/**
 * Unified Exercise & Mobility Stretch Library with Complete Kinesiological Data
 * Unifies all resistance training exercises, static stretches, dynamic warmups, and foam roll movements
 * into a single coherent schema with verified target muscles and anatomy diagrams.
 */

export interface UnifiedExerciseItem {
  id?: string;
  name: string;
  normalizedName: string;
  type: "EXERCISE" | "STRETCH" | "MOBILITY" | "CARDIO" | "WELLNESS";
  muscleGroup: string;
  equipment: string;
  category: "STRENGTH" | "BODYWEIGHT" | "CARDIO" | "STATIC_STRETCH" | "DYNAMIC_WARMUP" | "FOAM_ROLL" | "WELLNESS";
  primaryMuscles: string[];
  secondaryMuscles: string[];
  biomechanicsCue: string;
  steps: string[];
  commonMistakes: string[];
  breathingPattern: string;
  diagramUrl: string;
  diagramStatus: "APPROVED" | "PENDING_APPROVAL" | "REJECTED" | "NEEDS_REVISION";
  diagramNotes?: string;
  approvedByUserId?: string | null;
  approvedAt?: string | null;
  isCustom?: boolean;
  createdByUserId?: string | null;
  createdByUserRole?: string;
}

export function normalizeExerciseName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
}

export const INITIAL_UNIFIED_EXERCISES: UnifiedExerciseItem[] = [
  // ==========================================
  // CHEST & PUSH EXERCISES
  // ==========================================
  {
    name: "Barbell Bench Press",
    normalizedName: "barbell_bench_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major (Sternal & Clavicular Heads)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii (Lateral/Medial Heads)", "Serratus Anterior"],
    biomechanicsCue: "Retract and depress scapulae, drive feet into the floor, flare lats, and touch lower sternum under control.",
    steps: [
      "Set Up: Lie flat on bench with eyes directly under the racked bar. Plant feet flat on floor.",
      "Grip: Grip bar slightly wider than shoulder-width with wrists stacked over elbows.",
      "Descent: Unrack bar, pull shoulder blades together, and lower bar in a slight arc to the lower sternum/xiphoid process.",
      "Drive: Press bar up and slightly back toward eye line while squeezing chest and locking elbows at top.",
    ],
    commonMistakes: [
      "Flaring elbows out at 90° (places high shear stress on anterior shoulder capsule).",
      "Bouncing the bar off the ribcage.",
      "Lifting hips off the bench during heavy drive.",
    ],
    breathingPattern: "Inhale deeply at the top to create intra-abdominal pressure → Lower bar with held breath → Exhale forcefully past the sticking point.",
    diagramUrl: "/anatomy/bench.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Incline Barbell Bench Press",
    normalizedName: "incline_barbell_bench_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major (Clavicular 'Upper' Head)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii", "Serratus Anterior"],
    biomechanicsCue: "Set bench to 30-45°. Lower bar to upper clavicular notch without flaring elbows.",
    steps: [
      "Set Up: Position bench at 30° to 45° angle. Plant heels firmly on floor.",
      "Unrack: Retract scapulae and press bar to full arm extension above upper chest.",
      "Eccentric: Lower smoothly to upper chest / clavicle area.",
      "Concentric: Drive upward without rounding shoulders forward.",
    ],
    commonMistakes: [
      "Bench angle too steep (>45° turns it into an anterior delt press).",
      "Excessive arching that turns incline into a flat press.",
    ],
    breathingPattern: "Inhale on descent → Exhale as bar passes sticking point.",
    diagramUrl: "/anatomy/incline_bench.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Flat Dumbbell Press",
    normalizedName: "flat_dumbbell_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii", "Coracobrachialis"],
    biomechanicsCue: "Allows natural converging pressing arc and deeper stretch without fixed barbell constraints.",
    steps: [
      "Set Up: Kick dumbbells up to shoulders as you lie back onto flat bench.",
      "Descent: Lower dumbbells with 45° elbow tuck until thumbs graze outer chest.",
      "Press: Drive up and slightly inward in an arc, squeezing pecs at the apex.",
    ],
    commonMistakes: [
      "Clanging dumbbells together at top (removes muscle tension).",
      "Wrists collapsing backward.",
    ],
    breathingPattern: "Inhale down into deep chest stretch → Exhale as you press up.",
    diagramUrl: "/anatomy/flat_dumbbell_press.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Push-Up",
    normalizedName: "push_up",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoid", "Rectus Abdominis", "Serratus Anterior"],
    biomechanicsCue: "Rigid plank line from crown of head to heels. Tuck elbows 45° like an arrow, not a 'T'.",
    steps: [
      "Start in high plank with hands slightly wider than shoulder width.",
      "Lower chest until 1 inch off floor while keeping glutes and core braced.",
      "Press floor away until elbows fully lock out with protraction at the top.",
    ],
    commonMistakes: [
      "Sagging lumbar spine / drooping hips.",
      "Head jutting forward to fake depth.",
    ],
    breathingPattern: "Inhale on lowering → Exhale as you push up.",
    diagramUrl: "/anatomy/push_up.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Chest Dip",
    normalizedName: "chest_dip",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Lower Pectoralis Major (Sternal Head)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii", "Rhomboids"],
    biomechanicsCue: "Lean torso 30° forward, flare elbows slightly out, and lower until shoulders pass elbows for deep sternal pec stretch.",
    steps: [
      "Mount parallel dip bars and lock elbows.",
      "Lean upper torso 30° forward with chin tucked.",
      "Lower body under control to a 90° elbow angle.",
      "Press back up to lockout while maintaining forward torso tilt.",
    ],
    commonMistakes: [
      "Staying completely upright (shifts focus to triceps).",
      "Dropping too fast into shoulder joint hyperextension.",
    ],
    breathingPattern: "Inhale on descent → Exhale on pressing up.",
    diagramUrl: "/anatomy/chest_dip.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // BACK & PULL EXERCISES
  // ==========================================
  {
    name: "Barbell Deadlift",
    normalizedName: "barbell_deadlift",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Gluteus Maximus", "Hamstrings (Biceps Femoris, Semitendinosus)", "Erector Spinae"],
    secondaryMuscles: ["Latissimus Dorsi", "Trapezius (Upper/Middle)", "Quadriceps", "Forearms (Grip)"],
    biomechanicsCue: "Wedge hips down into the bar, pull slack out with a metallic 'click', and push the floor away like a leg press.",
    steps: [
      "Set Up: Bar over mid-foot (1 inch from shins). Feet hip-width apart.",
      "Grip: Hinge at hips and grip bar just outside knees.",
      "Wedge: Pull chest proud, engage lats, drop hips until shins touch the bar.",
      "Drive: Push floor away through mid-foot, driving hips forward into lockout.",
    ],
    commonMistakes: [
      "Rounding lumbar spine under heavy load.",
      "Yanking the bar abruptly without pulling slack first.",
      "Hyperextending lower back at lockout.",
    ],
    breathingPattern: "Big diaphragmatic inhale into belt at bottom → Hold breath during lift → Exhale at lockout.",
    diagramUrl: "/anatomy/deadlift.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Barbell Bent-Over Row",
    normalizedName: "barbell_bent_over_row",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle & Lower Trapezius"],
    secondaryMuscles: ["Posterior Deltoid", "Biceps Brachii", "Brachialis", "Erector Spinae"],
    biomechanicsCue: "Hinge torso to 45°, pull elbows toward hips/navel, and squeeze shoulder blades together.",
    steps: [
      "Hinge hips back with knees soft until torso is at 45° angle.",
      "Pull bar into lower ribcage/navel by driving elbows back.",
      "Squeeze rhomboids and lats for 1 second at top.",
      "Lower bar slowly with full lat stretch at bottom.",
    ],
    commonMistakes: [
      "Using excessive torso jerk to bounce the bar.",
      "Pulling to clavicle instead of navel.",
    ],
    breathingPattern: "Inhale at bottom stretch → Exhale as you pull bar to torso.",
    diagramUrl: "/anatomy/barbell_row.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Lat Pulldown (Wide Grip)",
    normalizedName: "lat_pulldown_wide_grip",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Latissimus Dorsi (Outer Flare)"],
    secondaryMuscles: ["Teres Major", "Biceps Brachii", "Brachioradialis", "Lower Trapezius"],
    biomechanicsCue: "Lean back 10-15°, drive elbows straight down into back pockets, and lead with proud chest.",
    steps: [
      "Grip bar with overhand grip 1.5x shoulder width.",
      "Secure thighs under thigh pad.",
      "Depress scapulae and pull bar down to upper clavicle.",
      "Resist the cable smoothly back to full overhead stretch.",
    ],
    commonMistakes: [
      "Leaning back 45° turning pulldown into a sloppy row.",
      "Pulling bar behind the neck.",
    ],
    breathingPattern: "Inhale at overhead stretch → Exhale as you pull to chest.",
    diagramUrl: "/anatomy/lat_pulldown.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Pull-Up",
    normalizedName: "pull_up",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Biceps Brachii", "Rhomboids", "Lower Trapezius", "Core"],
    biomechanicsCue: "Full dead hang to chin over bar. Initiate by depressing scapulae before bending elbows.",
    steps: [
      "Hang from overhead bar with pronated grip wider than shoulders.",
      "Set shoulder blades down and back.",
      "Pull chest to bar until chin clears bar height.",
      "Lower with controlled 3-second descent back to dead hang.",
    ],
    commonMistakes: [
      "Kipping or swinging legs.",
      "Cutting range of motion at bottom or top.",
    ],
    breathingPattern: "Inhale at bottom hang → Exhale as you pull chin over bar.",
    diagramUrl: "/anatomy/pull_up.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Face Pull",
    normalizedName: "face_pull",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Posterior Deltoids", "Infraspinatus", "Teres Minor"],
    secondaryMuscles: ["Middle/Lower Trapezius", "Rhomboids"],
    biomechanicsCue: "Set cable at eye level. Pull center of rope to bridge of nose while externally rotating thumbs back.",
    steps: [
      "Attach rope to eye-level cable with overhand/neutral thumbs-back grip.",
      "Step back for tension, pull rope toward forehead while separating hands outward.",
      "Hold external rotation squeeze for 1 second.",
      "Control cable back to straight arm stretch.",
    ],
    commonMistakes: [
      "Pulling downward to neck instead of outward to forehead.",
      "Using heavy momentum and hyperextending lower back.",
    ],
    breathingPattern: "Inhale at reach → Exhale as hands pull back to ears.",
    diagramUrl: "/anatomy/face_pull.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // LEGS & LOWER BODY
  // ==========================================
  {
    name: "Barbell Back Squat",
    normalizedName: "barbell_back_squat",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps Femoris (Vastus Lateralis, Medialis, Intermedius, Rectus Femoris)", "Gluteus Maximus"],
    secondaryMuscles: ["Adductor Magnus", "Hamstrings", "Erector Spinae", "Transverse Abdominis"],
    biomechanicsCue: "Break at hips and knees simultaneously. Spread the floor with feet, driving knees out in line with toes.",
    steps: [
      "Bar positioned across upper traps. Unrack and take 3 deliberate setup steps.",
      "Brace core 360°, descend until hip crease is below top of knees (parallel).",
      "Drive out of the hole by pressing through full foot, maintaining proud chest.",
    ],
    commonMistakes: [
      "Knees caving inward (valgus collapse).",
      "Heels lifting off the floor.",
      "'Good-morning' squatting where hips shoot up first.",
    ],
    breathingPattern: "Big belly inhale at top → Hold intra-abdominal pressure through bottom turn → Exhale past sticking point.",
    diagramUrl: "/anatomy/squat.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Bulgarian Split Squat",
    normalizedName: "bulgarian_split_squat",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps Femoris", "Gluteus Maximus"],
    secondaryMuscles: ["Gluteus Medius", "Adductors", "Hamstrings", "Core"],
    biomechanicsCue: "Rear foot on bench with laces down. Pitch torso forward 15° for glute bias or stay upright for quad bias.",
    steps: [
      "Place top of rear foot flat on bench 2-3 feet behind working front leg.",
      "Descend smoothly until front thigh is parallel to floor and rear knee hovers 1 inch off ground.",
      "Drive straight through front mid-foot and heel to return to top.",
    ],
    commonMistakes: [
      "Pushing off rear leg instead of loading front foot.",
      "Front heel lifting off floor.",
    ],
    breathingPattern: "Inhale on descent → Exhale as you drive through front foot.",
    diagramUrl: "/anatomy/bulgarian_split_squat.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Leg Extension",
    normalizedName: "leg_extension",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps (Rectus Femoris, Vastus Lateralis, Vastus Medialis, Vastus Intermedius)"],
    secondaryMuscles: ["Tibialis Anterior", "Tensor Fasciae Latae"],
    biomechanicsCue: "Align knee joint axis with machine pivot point. Flex quads to full terminal knee extension and hold for 1 second.",
    steps: [
      "Adjust back pad so back of knee rests comfortably against seat edge.",
      "Pad sits above ankles on lower shins.",
      "Extend legs upward smoothly without kicking or using momentum.",
      "Hold full peak contraction at the top for 1 full second, then lower under 3-second control.",
    ],
    commonMistakes: [
      "Using explosive momentum instead of controlled quad contraction.",
      "Butt lifting off the seat on heavy reps.",
    ],
    breathingPattern: "Inhale at bottom → Exhale as you extend legs to lockout.",
    diagramUrl: "/anatomy/leg_extension.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Lying / Seated Leg Curl",
    normalizedName: "leg_curl",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus)"],
    secondaryMuscles: ["Gastrocnemius (Calf Assistance)", "Sartorius", "Gracilis"],
    biomechanicsCue: "Align knee with pivot point. Curl pad toward glutes, dorsiflexing ankles for maximum hamstring isolation.",
    steps: [
      "Position pad just below calves/Achilles tendon.",
      "Keep hips firmly pressed down into pad.",
      "Curl heels up toward glutes through complete knee flexion range.",
      "Lower resistance slowly over 3 seconds under full tension.",
    ],
    commonMistakes: [
      "Arching lower back and lifting hips off bench to cheat weight.",
      "Allowing weight stack to slam at bottom.",
    ],
    breathingPattern: "Inhale on eccentric descent → Exhale on curling heels to glutes.",
    diagramUrl: "/anatomy/leg_curl.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Standing Calf Raise",
    normalizedName: "standing_calf_raise",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Gastrocnemius (Medial & Lateral Heads)"],
    secondaryMuscles: ["Soleus", "Plantaris", "Tibialis Posterior", "Peroneus Longus"],
    biomechanicsCue: "Drop heels into deep 3-second calf stretch below platform level, then explode onto balls of big toes for 2-second peak contraction.",
    steps: [
      "Balls of feet on edge of platform with balls of big toes anchored.",
      "Keep knees straight but not hyperextended.",
      "Lower heels deeply below platform into full stretch for 2 seconds.",
      "Drive onto big toe joints, holding peak contraction at apex for 2 seconds.",
    ],
    commonMistakes: [
      "Bouncing fast at bottom using Achilles tendon elasticity rather than muscle fibers.",
      "Bending knees during standing raises (shifts load away from gastrocnemius).",
    ],
    breathingPattern: "Inhale on bottom stretch → Exhale as you rise onto toes.",
    diagramUrl: "/anatomy/standing_calf_raise.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hip Thrust",
    normalizedName: "hip_thrust",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings", "Adductor Magnus", "Quadriceps"],
    biomechanicsCue: "Upper back across bench, chin tucked. Drive through heels to full horizontal hip extension without hyperextending lumbar spine.",
    steps: [
      "Sit on floor with upper back against bench and loaded barbell across hip crease.",
      "Feet shoulder-width apart, shins vertical at top of movement.",
      "Drive through heels to extend hips until thighs and torso form a straight tabletop.",
      "Squeeze glutes hard at top for 2 seconds with eyes forward.",
    ],
    commonMistakes: [
      "Looking up at ceiling and hyperextending lumbar spine.",
      "Feet placed too far forward or too close to hips.",
    ],
    breathingPattern: "Inhale on lowering → Exhale as you thrust hips upward.",
    diagramUrl: "/anatomy/hip_thrust.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Romanian Deadlift (RDL)",
    normalizedName: "romanian_deadlift_rdl",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Hamstrings (Biceps Femoris)", "Gluteus Maximus"],
    secondaryMuscles: ["Erector Spinae", "Adductor Magnus", "Latissimus Dorsi"],
    biomechanicsCue: "Keep soft bend in knees, push hips back to wall behind you, and keep bar scraping down thighs.",
    steps: [
      "Stand tall holding barbell with overhand grip at hips.",
      "With slight knee bend, push hips straight back while lowering bar along thighs.",
      "Stop when hips cannot travel further back (mid-shin level) and hamstrings are fully stretched.",
      "Drive hips forward to stand tall, squeezing glutes.",
    ],
    commonMistakes: [
      "Bending knees excessively turning it into a squat.",
      "Allowing bar to drift away from legs.",
      "Rounding lumbar spine.",
    ],
    breathingPattern: "Inhale on hip hinge descent → Exhale as hips drive through to top.",
    diagramUrl: "/anatomy/romanian_deadlift.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // SHOULDERS & ARMS
  // ==========================================
  {
    name: "Overhead Shoulder Press",
    normalizedName: "overhead_shoulder_press",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Anterior Deltoid", "Lateral Deltoid"],
    secondaryMuscles: ["Triceps Brachii", "Upper Trapezius", "Serratus Anterior", "Core"],
    biomechanicsCue: "Brace glutes and core. Press bar in vertical path over ears with head pushing through window at lockout.",
    steps: [
      "Bar resting across front delts/clavicle with grip just outside shoulders.",
      "Brace glutes and core to prevent lumbar hyperextension.",
      "Press bar vertically, moving head back slightly to clear chin.",
      "Lock bar out directly over middle of foot/head.",
    ],
    commonMistakes: [
      "Excessive backward lean turning press into an incline bench.",
      "Pressing bar forward in an arc rather than straight up.",
    ],
    breathingPattern: "Inhale at clavicle → Exhale as bar reaches overhead lockout.",
    diagramUrl: "/anatomy/overhead_press.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Dumbbell Lateral Raise",
    normalizedName: "dumbbell_lateral_raise",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Lateral Deltoid (Middle Head)"],
    secondaryMuscles: ["Anterior Deltoid", "Supraspinatus", "Upper Trapezius"],
    biomechanicsCue: "Slight 15° forward lean. Raise dumbbells in scapular plane (30° forward) leading with elbows, not wrists.",
    steps: [
      "Stand with dumbbells at sides, slight hinge forward at hips.",
      "Raise arms out to sides in scapular plane until parallel to floor.",
      "Pour the pitcher slightly with pinkies high.",
      "Lower under control over 2 seconds.",
    ],
    commonMistakes: [
      "Using torso swinging momentum.",
      "Shrugging upper traps to lift the dumbbells.",
    ],
    breathingPattern: "Inhale at bottom → Exhale as arms raise to shoulder height.",
    diagramUrl: "/anatomy/lateral_raise.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Barbell Bicep Curl",
    normalizedName: "barbell_bicep_curl",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Biceps Brachii (Short & Long Heads)"],
    secondaryMuscles: ["Brachialis", "Brachioradialis", "Forearm Flexors"],
    biomechanicsCue: "Elbows pinned to ribcage. Curl bar through full elbow flexion without swinging hips.",
    steps: [
      "Stand tall holding barbell with shoulder-width underhand grip.",
      "Keep elbows fixed at sides.",
      "Curl bar upward toward shoulders, squeezing biceps at top.",
      "Lower slowly over 3 seconds to full arm extension.",
    ],
    commonMistakes: [
      "Swinging hips and lower back.",
      "Allowing elbows to drift far forward.",
    ],
    breathingPattern: "Inhale on descent → Exhale as bar curls up.",
    diagramUrl: "/anatomy/bicep_curl.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Dumbbell Hammer Curl",
    normalizedName: "dumbbell_hammer_curl",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps Brachii (Long Head)", "Forearm Extensors"],
    biomechanicsCue: "Neutral palms-facing grip. Builds upper arm thickness and forearm grip strength.",
    steps: [
      "Hold dumbbells at sides with palms facing inward (neutral grip).",
      "Curl weights up while keeping palms facing each other.",
      "Squeeze brachialis at apex of curl.",
      "Lower smoothly to full extension.",
    ],
    commonMistakes: [
      "Pronating or supinating wrists during movement.",
      "Using shoulder momentum.",
    ],
    breathingPattern: "Inhale down → Exhale curling up.",
    diagramUrl: "/anatomy/hammer_curl.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Cable Tricep Pushdown",
    normalizedName: "cable_tricep_pushdown",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Triceps Brachii (Lateral & Medial Heads)"],
    secondaryMuscles: ["Triceps Brachii (Long Head)", "Anconeus"],
    biomechanicsCue: "Lock elbows at sides of torso. Push straight down, flaring rope or bar at bottom for full tricep lockout.",
    steps: [
      "Stand with slight forward lean, gripping rope or straight bar at chest height.",
      "Keep upper arms pinned to sides.",
      "Extend elbows down until arms are completely straight.",
      "Return slowly to 90° elbow flexion.",
    ],
    commonMistakes: [
      "Flaring elbows outward.",
      "Letting shoulders roll forward to press with bodyweight.",
    ],
    breathingPattern: "Inhale on bend → Exhale on extension lockout.",
    diagramUrl: "/anatomy/tricep_pushdown.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // CORE & LOWER BACK
  // ==========================================
  {
    name: "Plank",
    normalizedName: "plank",
    type: "EXERCISE",
    muscleGroup: "Core",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis"],
    secondaryMuscles: ["Internal & External Obliques", "Quadriceps", "Gluteus Maximus", "Serratus Anterior"],
    biomechanicsCue: "Forearms on ground, elbows under shoulders. Squeeze glutes, pull belly button to spine, and create full-body tension.",
    steps: [
      "Position forearms on floor with elbows directly under shoulders.",
      "Extend legs back with toes tucked.",
      "Maintain straight line from crown of head to heels without letting hips dip or spike.",
      "Hold with steady diaphragmatic breathing.",
    ],
    commonMistakes: [
      "Sagging lower back (lumbar extension).",
      "Holding breath (maintain steady diaphragmatic breathing).",
    ],
    breathingPattern: "Steady rhythmic nose inhalations and pursed lip exhalations while maintaining 360° abdominal brace.",
    diagramUrl: "/anatomy/plank.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hyperextensions (Back Extension)",
    normalizedName: "hyperextensions_back_extension",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Bodyweight",
    category: "STRENGTH",
    primaryMuscles: ["Erector Spinae (Spinalis, Longissimus, Iliocostalis)", "Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus)", "Quadratus Lumborum"],
    biomechanicsCue: "Hinge at hips over the 45° roman chair pad. Extend spine smoothly to neutral alignment without hyperextending neck.",
    steps: [
      "Position thighs against pad with pelvis slightly clear of front edge.",
      "Cross arms over chest or hold plate; hinge forward at hips until 90° bend.",
      "Engage glutes and lower back to raise torso in line with legs.",
      "Squeeze glutes and erectors for 1 full second at parallel.",
    ],
    commonMistakes: [
      "Aggressively arching lower back past neutral.",
      "Jerking head backward.",
    ],
    breathingPattern: "Inhale on descent → Exhale as you extend spine to neutral.",
    diagramUrl: "/anatomy/back_hyperextension.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "QL Extension (Side Roman Chair)",
    normalizedName: "ql_extension_side_roman_chair",
    type: "EXERCISE",
    muscleGroup: "Core",
    equipment: "Bodyweight",
    category: "STRENGTH",
    primaryMuscles: ["Quadratus Lumborum (Deep Lateral Spine Stabilizer)", "Internal & External Obliques"],
    secondaryMuscles: ["Gluteus Medius", "Erector Spinae", "Tensor Fasciae Latae"],
    biomechanicsCue: "Side-lying on 45° hyper bench with lateral hip pad support. Lower torso laterally toward floor and flex side obliques and deep QL to neutral horizontal line.",
    steps: [
      "Position body side-lying on 45° roman chair with hip bone supported against pad.",
      "Anchor top foot behind bottom foot against footplates.",
      "Cross hands over chest; lower torso sideways toward floor under 3-second control.",
      "Contract lateral abdominal wall and QL to raise torso back to horizontal alignment.",
    ],
    commonMistakes: [
      "Twisting shoulders forward instead of maintaining strict pure lateral plane.",
      "Jerking head or pulling neck.",
    ],
    breathingPattern: "Inhale on lateral descent stretch → Exhale as you contract obliques and QL to parallel.",
    diagramUrl: "/anatomy/ql_extension.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // COMPREHENSIVE MOBILITY & STRETCHES (ALL MUSCLE GROUPS)
  // ==========================================

  // 1. CHEST & ANTERIOR SHOULDER STRETCHES
  {
    name: "Chest Doorway Stretch",
    normalizedName: "chest_doorway_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Pectoralis Major", "Pectoralis Minor"],
    secondaryMuscles: ["Anterior Deltoid", "Coracobrachialis", "Biceps Brachii (Short Head)"],
    biomechanicsCue: "Forearm flush against door frame at 90°. Step forward with same-side foot, turning torso away until deep chest stretch is felt.",
    steps: [
      "Stand in doorway; place forearm flat against door jamb with elbow bent 90°.",
      "Step forward with same side foot.",
      "Gently rotate torso away from door frame until chest and shoulder open up.",
      "Hold for 30-45 seconds, then repeat on opposite side.",
    ],
    commonMistakes: [
      "Shrugging shoulder up toward ear (keep scapula depressed).",
      "Arching lower back instead of opening chest.",
    ],
    breathingPattern: "Inhale tall through spine → Exhale as chest relaxes deeper into doorway stretch.",
    diagramUrl: "/anatomy/chest_doorway_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Band Shoulder Dislocates & Pass-Throughs",
    normalizedName: "band_shoulder_dislocates",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Pectoralis Minor", "Anterior Deltoid", "Scapular Mobilizers"],
    secondaryMuscles: ["Rotator Cuff", "Rhomboids", "Serratus Anterior"],
    biomechanicsCue: "Grip light band or PVC wide. Rotate arms overhead and behind back with straight elbows in a continuous smooth circle.",
    steps: [
      "Hold band wide with overhand grip in front of hips.",
      "Keeping elbows straight, raise arms up and overhead.",
      "Continue rotation behind back until band touches glutes.",
      "Reverse movement back to front for 10 smooth repetitions.",
    ],
    commonMistakes: [
      "Bending elbows to force tight range.",
      "Arching lower back excessively.",
    ],
    breathingPattern: "Inhale as band passes overhead → Exhale as band lowers behind back.",
    diagramUrl: "/anatomy/band_pass_throughs.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 2. BACK, LATS, NECK & THORACIC SPINE
  {
    name: "Lat Hang & Side Reach Stretch",
    normalizedName: "lat_hang_side_reach_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Thoracolumbar Fascia", "Intercostals", "Serratus Anterior"],
    biomechanicsCue: "Grasp overhead bar or sturdy post, sit hips back, and reach diagonally across body to decompress lat fibers.",
    steps: [
      "Grasp vertical post or pull-up bar with one hand.",
      "Hinge hips back and away while letting torso sink toward floor.",
      "Breathe deeply into lateral ribcage for 45 seconds.",
      "Repeat on opposite side.",
    ],
    commonMistakes: [
      "Shrugging shoulder blade up toward ear.",
      "Holding breath during deep lateral stretch.",
    ],
    breathingPattern: "Deep nasal inhale expanding ribcage → Long relaxing exhale sinking hips deeper.",
    diagramUrl: "/anatomy/lat_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Child's Pose Lat & Spine Stretch",
    normalizedName: "childs_pose_lat_spine_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Latissimus Dorsi", "Erector Spinae", "Thoracolumbar Fascia"],
    secondaryMuscles: ["Gluteus Maximus", "Posterior Deltoid"],
    biomechanicsCue: "Knees wide, big toes together. Sit hips back onto heels, reach arms forward, and walk hands diagonally to side for deep lat stretch.",
    steps: [
      "Kneel on mat with knees wide and big toes touching.",
      "Sit hips back onto heels and extend arms forward on floor.",
      "Walk hands diagonally to right side to stretch left lat, holding 30 seconds.",
      "Walk hands to left side to stretch right lat.",
    ],
    commonMistakes: [
      "Lifting hips off heels.",
      "Tensing shoulders up into neck.",
    ],
    breathingPattern: "Slow diaphragmatic inhalations filling lower back → Relaxing exhalations sinking into floor.",
    diagramUrl: "/anatomy/childs_pose.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Upper Trap & Levator Scapulae Neck Stretch",
    normalizedName: "upper_trap_levator_scapulae_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Upper Trapezius", "Levator Scapulae"],
    secondaryMuscles: ["Sternocleidomastoid", "Scalenes"],
    biomechanicsCue: "Sit tall. Gently guide ear toward shoulder, depressing opposite shoulder down toward floor.",
    steps: [
      "Sit upright in chair or floor with neutral spine.",
      "Anchor right hand under chair edge or behind back.",
      "Gently tilt head left, bringing left ear toward left shoulder.",
      "Hold for 30 seconds without forcing, then turn chin toward armpit for levator scapulae.",
    ],
    commonMistakes: [
      "Pulling forcefully on head (use only gentle weight of hand).",
      "Letting opposite shoulder shrug up.",
    ],
    breathingPattern: "Slow steady nasal breathing throughout.",
    diagramUrl: "/anatomy/neck_trap_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Cat-Cow Spine Mobility",
    normalizedName: "cat_cow_spine_mobility",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Erector Spinae", "Rectus Abdominis", "Thoracolumbar Fascia"],
    secondaryMuscles: ["Serratus Anterior", "Rhomboids", "Neck Extensors & Flexors"],
    biomechanicsCue: "Sync movement with breath. Cow: inhale, drop belly, look up. Cat: exhale, round spine, push floor away.",
    steps: [
      "Start on all fours with hands under shoulders, knees under hips.",
      "Cow: Inhale, arch back, drop belly, lift tailbone and gaze upward.",
      "Cat: Exhale, tuck tailbone, round spine to ceiling, tuck chin to chest.",
      "Flow continuously through 8-10 cycles smoothly.",
    ],
    commonMistakes: [
      "Bending elbows instead of moving spine.",
      "Rushing repetitions without breath synchronization.",
    ],
    breathingPattern: "Inhale on Cow (extension) → Exhale forcefully on Cat (flexion).",
    diagramUrl: "/anatomy/cat_cow.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Foam Roll Thoracic Spine",
    normalizedName: "foam_roll_thoracic_spine",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "FOAM_ROLL",
    primaryMuscles: ["Thoracic Spine Extensors", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Latissimus Dorsi", "Posterior Deltoid"],
    biomechanicsCue: "Foam roller across mid-back. Support head with hands, hug elbows together to expose rhomboids, and roll smoothly from mid-back to top of shoulders.",
    steps: [
      "Lie with foam roller across middle back below shoulder blades.",
      "Support head with hands, lift hips slightly off floor.",
      "Roll slowly back and forth over upper back for 60 seconds.",
      "Pause on tight spots and extend upper back over roller for 3 breaths.",
    ],
    commonMistakes: [
      "Rolling onto lower lumbar spine (keep roller above bottom rib).",
      "Pulling neck with hands.",
    ],
    breathingPattern: "Slow, rhythmic deep breathing throughout rolling.",
    diagramUrl: "/anatomy/foam_roll_thoracic.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Thread the Needle (Thoracic Rotation)",
    normalizedName: "thread_the_needle_thoracic_rotation",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Thoracic Spine Rotators", "Posterior Deltoid", "Rhomboids"],
    secondaryMuscles: ["Middle Trapezius", "Infraspinatus"],
    biomechanicsCue: "Quadruped position. Slide right arm under left armpit along floor, resting temple on mat while opening mid-back.",
    steps: [
      "Start on all fours.",
      "Slide right hand and arm under torso to the left until right shoulder and ear rest on mat.",
      "Press left hand gently into floor to deepen thoracic rotation.",
      "Hold for 30-45 seconds, then switch sides.",
    ],
    commonMistakes: [
      "Twisting hips excessively (keep hips squared over knees).",
      "Collapsing neck.",
    ],
    breathingPattern: "Inhale to set position → Exhale as shoulder melts into mat.",
    diagramUrl: "/anatomy/thread_the_needle.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 3. LEGS - QUADS & HIP FLEXORS
  {
    name: "Couch Stretch (Kneeling Quad & Hip Flexor)",
    normalizedName: "couch_stretch_kneeling_quad_hip_flexor",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Rectus Femoris", "Psoas Major", "Iliacus"],
    secondaryMuscles: ["Vastus Lateralis/Medialis", "Tensor Fasciae Latae", "Sartorius"],
    biomechanicsCue: "Rear knee against wall with shin vertical. Squeeze rear glute into posterior pelvic tilt, keeping torso tall without lumbar extension.",
    steps: [
      "Back knee against baseboard of wall with rear shin flat against wall.",
      "Step opposite foot forward into 90° lunge stance.",
      "Squeeze glute of back leg to drive hips forward into deep rectus femoris stretch.",
      "Hold for 45-60 seconds per side.",
    ],
    commonMistakes: [
      "Arching lower back instead of squeezing rear glute.",
      "Letting front knee cave inward.",
    ],
    breathingPattern: "Deep diaphragmatic inhale → Exhale relaxing deeper into hip extension.",
    diagramUrl: "/anatomy/couch_stretch.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Standing Quad Stretch",
    normalizedName: "standing_quad_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Quadriceps Femoris (Rectus Femoris, Vastus Lateralis, Medialis, Intermedius)"],
    secondaryMuscles: ["Iliopsoas", "Anterior Tibialis"],
    biomechanicsCue: "Hold foot behind glute, keep knees aligned together, and tuck tailbone under (posterior pelvic tilt).",
    steps: [
      "Stand tall on one leg (hold wall for balance).",
      "Grab top of opposite ankle and draw heel to glute.",
      "Keep both knees side by side and contract glutes.",
      "Hold for 30-45 seconds per leg.",
    ],
    commonMistakes: [
      "Letting knee drift forward or flare out sideways.",
      "Excessive lumbar arching.",
    ],
    breathingPattern: "Steady rhythmic breathing throughout.",
    diagramUrl: "/anatomy/standing_quad_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Frog Stretch (Deep Adductor & Groin)",
    normalizedName: "frog_stretch_deep_adductor_groin",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Adductor Longus", "Adductor Magnus", "Gracilis"],
    secondaryMuscles: ["Pectineus", "Deep Hip Rotators", "Pelvic Floor"],
    biomechanicsCue: "Knees placed wide on padded mat with ankles turned outward. Slowly sit hips backward toward heels to open adductors.",
    steps: [
      "Get on all fours and spread knees as wide as comfortably possible.",
      "Turn feet out so inner ankles and arches touch the floor.",
      "Rest forearms on floor and gently push hips back toward heels.",
      "Hold for 45-60 seconds.",
    ],
    commonMistakes: [
      "Allowing feet to tuck inward (keep ankles turned out 90°).",
      "Forcing painful hip joint compression.",
    ],
    breathingPattern: "Slow deep nasal inhalations → Relaxing out-breaths sinking hips backward.",
    diagramUrl: "/anatomy/frog_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 4. LEGS - HAMSTRINGS, GLUTES & HIPS
  {
    name: "Pigeon Stretch",
    normalizedName: "pigeon_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Piriformis", "Deep Hip External Rotators", "Gluteus Medius"],
    secondaryMuscles: ["Gluteus Maximus", "Psoas Major", "Tensor Fasciae Latae"],
    biomechanicsCue: "Front shin at 45-90° across mat. Square both hip bones to the floor, breathing deeply into the outer hip capsule.",
    steps: [
      "From quadruped or downward dog, bring right knee forward behind right wrist.",
      "Angle right foot across toward left hand, extending left leg straight back.",
      "Square hips toward the floor and lower torso forward over front shin.",
      "Hold for 45-60 seconds per side while taking deep belly breaths.",
    ],
    commonMistakes: [
      "Rolling onto outer hip of front leg (keeps hips from squaring).",
      "Torquing front knee (keep front ankle flexed to protect joint).",
    ],
    breathingPattern: "4-second deep nasal inhale → 6-second relaxing exhale, melting deeper into the hip capsule.",
    diagramUrl: "/anatomy/pigeon.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Figure 4 Glute & Piriformis Stretch",
    normalizedName: "figure_4_glute_piriformis_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Gluteus Medius", "Piriformis", "Gluteus Maximus"],
    secondaryMuscles: ["Iliotibial Band", "Obturator Internus"],
    biomechanicsCue: "Lie on back, cross ankle over opposite knee. Thread hands behind hamstring and draw knee toward chest.",
    steps: [
      "Lie supine with knees bent and feet flat on floor.",
      "Cross right ankle over left knee.",
      "Reach hands through legs and grasp back of left thigh.",
      "Pull left thigh toward chest until stretch is felt in right outer hip.",
    ],
    commonMistakes: [
      "Lifting head and shoulders off mat (keep spine relaxed).",
      "Twisting pelvis to one side.",
    ],
    breathingPattern: "Inhale relax → Exhale gently drawing thigh closer.",
    diagramUrl: "/anatomy/figure4_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "90/90 Hip Mobility Flow",
    normalizedName: "hip_90_90_mobility_flow",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Hip Internal Rotators", "Hip External Rotators", "Gluteus Medius"],
    secondaryMuscles: ["Piriformis", "Psoas", "Adductors"],
    biomechanicsCue: "Both front and rear legs bent at 90° angles on floor. Sit tall through spine and fold smoothly over front shin.",
    steps: [
      "Sit on floor with lead leg in front bent at 90° and trail leg to side bent at 90°.",
      "Sit tall with proud chest.",
      "Hinge at hips to fold chest forward over front shin for 30 seconds.",
      "Sit upright and rotate hips to switch sides smoothly.",
    ],
    commonMistakes: [
      "Rounding thoracic spine instead of hinging at hips.",
      "Slumping weight entirely to one side.",
    ],
    breathingPattern: "Inhale tall → Exhale folding over front shin.",
    diagramUrl: "/anatomy/hip_90_90.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hamstring Standing Fold",
    normalizedName: "hamstring_standing_fold",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus)"],
    secondaryMuscles: ["Gastrocnemius", "Erector Spinae", "Gluteus Maximus"],
    biomechanicsCue: "Hinge at hips with soft knees. Let head hang heavy, reaching chest toward shins.",
    steps: [
      "Stand tall with feet hip-width apart.",
      "Hinge at hips, folding upper body over thighs.",
      "Let head and arms hang freely toward the floor.",
      "Hold for 45 seconds, relaxing deeper on each exhale.",
    ],
    commonMistakes: [
      "Locking knees backward into hyperextension.",
      "Straining neck by looking forward.",
    ],
    breathingPattern: "Inhale to lengthen spine → Exhale to fold deeper toward thighs.",
    diagramUrl: "/anatomy/hamstring_fold.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Seated Butterfly Adductor Stretch",
    normalizedName: "seated_butterfly_adductor_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Adductor Longus", "Adductor Brevis", "Gracilis"],
    secondaryMuscles: ["Pectineus", "Gluteus Medius"],
    biomechanicsCue: "Soles of feet pressed together. Sit tall and gently allow gravity to lower knees toward floor.",
    steps: [
      "Sit tall on mat; bring soles of feet together in front of pelvis.",
      "Hold feet with hands and lengthen spine.",
      "Gently press knees toward floor, hinging slightly forward at hips.",
      "Hold for 45 seconds.",
    ],
    commonMistakes: [
      "Aggressively pushing knees down with elbows.",
      "Hunching upper back.",
    ],
    breathingPattern: "Deep nasal inhalations lengthening spine → Exhalations opening groin.",
    diagramUrl: "/anatomy/butterfly_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Calf Wall Stretch (Gastrocnemius & Soleus)",
    normalizedName: "calf_wall_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Gastrocnemius (Medial & Lateral)", "Soleus"],
    secondaryMuscles: ["Achilles Tendon", "Plantaris", "Tibialis Posterior"],
    biomechanicsCue: "Back leg straight with heel flat on floor to stretch gastrocnemius; slightly bend back knee to stretch soleus.",
    steps: [
      "Place hands flat on wall at shoulder height.",
      "Step right foot back, keeping heel flat and toes pointing forward.",
      "Lean weight forward into front knee until calf stretch is felt in back leg.",
      "Hold 30 seconds with back knee straight, then 30 seconds with slight knee bend.",
    ],
    commonMistakes: [
      "Letting back heel lift off floor.",
      "Turning back toes outward.",
    ],
    breathingPattern: "Steady rhythmic breathing throughout.",
    diagramUrl: "/anatomy/calf_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 5. SHOULDERS & ROTATOR CUFF
  {
    name: "Cross-Body Shoulder Stretch",
    normalizedName: "cross_body_shoulder_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Posterior Deltoid", "Infraspinatus"],
    secondaryMuscles: ["Teres Minor", "Rhomboids", "Middle Trapezius"],
    biomechanicsCue: "Draw arm horizontally across chest with opposite hand, depressing shoulder down away from ear.",
    steps: [
      "Stand tall; bring right arm straight across chest at shoulder height.",
      "Use left forearm to gently hug right arm closer to chest.",
      "Keep right shoulder packed down.",
      "Hold for 30 seconds per side.",
    ],
    commonMistakes: [
      "Allowing shoulder to shrug up toward ear.",
      "Twisting torso to follow the arm.",
    ],
    breathingPattern: "Inhale tall → Exhale drawing arm closer to chest.",
    diagramUrl: "/anatomy/shoulder_crossbody.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Sleeper Rotator Cuff Stretch",
    normalizedName: "sleeper_rotator_cuff_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Infraspinatus", "Teres Minor (Posterior Rotator Cuff)"],
    secondaryMuscles: ["Posterior Deltoid", "Supraspinatus"],
    biomechanicsCue: "Side-lying on stretching shoulder with upper arm at 90°. Gently guide forearm down toward floor without rolling backward.",
    steps: [
      "Lie on right side with head supported on pillow.",
      "Right upper arm extended straight out from shoulder at 90° angle, elbow bent 90°.",
      "Use left hand to gently guide right wrist downward toward floor.",
      "Hold for 30-45 seconds, feeling gentle stretch in back of shoulder.",
    ],
    commonMistakes: [
      "Forcing forearm down aggressively (rotator cuff requires gentle stretch).",
      "Rolling shoulder blade off the floor.",
    ],
    breathingPattern: "Slow gentle breathing throughout.",
    diagramUrl: "/anatomy/sleeper_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 6. ARMS & FOREARMS
  {
    name: "Overhead Triceps Stretch",
    normalizedName: "overhead_triceps_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Triceps Brachii (Long Head)"],
    secondaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    biomechanicsCue: "Point elbow directly toward ceiling with hand reaching down between shoulder blades. Avoid overarching lower back.",
    steps: [
      "Raise right arm overhead and bend elbow, reaching right hand down upper back.",
      "Use left hand to gently press right elbow backward and downward.",
      "Hold for 30 seconds per arm.",
    ],
    commonMistakes: [
      "Arching lumbar spine excessively (brace core).",
      "Pushing head forward.",
    ],
    breathingPattern: "Inhale lengthen spine → Exhale deepening tricep stretch.",
    diagramUrl: "/anatomy/tricep_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Biceps Wall Stretch",
    normalizedName: "biceps_wall_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Biceps Brachii (Short & Long Heads)", "Brachialis"],
    secondaryMuscles: ["Anterior Deltoid", "Pectoralis Major", "Pronator Teres"],
    biomechanicsCue: "Place palm flat on wall at shoulder height with thumb pointing up. Rotate torso away until deep bicep stretch is felt.",
    steps: [
      "Stand perpendicular to wall.",
      "Place right palm flat against wall at shoulder height with arm fully extended.",
      "Gently rotate torso and feet to the left away from the wall.",
      "Hold for 30-45 seconds, then switch arms.",
    ],
    commonMistakes: [
      "Shrugging shoulder up.",
      "Bending elbow on wall.",
    ],
    breathingPattern: "Deep rhythmic breathing throughout.",
    diagramUrl: "/anatomy/bicep_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Wrist Flexor & Extensor Mobility",
    normalizedName: "wrist_flexor_extensor_mobility",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Flexor Carpi Radialis", "Flexor Digitorum", "Extensor Digitorum"],
    secondaryMuscles: ["Brachioradialis", "Pronator Teres"],
    biomechanicsCue: "Quadruped position. Place palms on floor with fingers pointing back toward knees; gently shift weight backward into heels.",
    steps: [
      "Get on all fours on a padded mat.",
      "Turn hands around so fingers point toward knees with palms flat.",
      "Gently shift hips backward until forearms feel a deep stretch.",
      "Hold for 20 seconds, then flip hands over onto knuckles/backs of hands for extensors.",
    ],
    commonMistakes: [
      "Locking elbows completely if hypermobile.",
      "Applying excessive bodyweight suddenly.",
    ],
    breathingPattern: "Gentle diaphragmatic breathing.",
    diagramUrl: "/anatomy/wrist_mobility.svg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // 7. CORE, QL & FULL BODY
  {
    name: "Cobra Abdominal Stretch",
    normalizedName: "cobra_abdominal_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Rectus Abdominis", "Psoas Major"],
    secondaryMuscles: ["Internal & External Obliques", "Thoracolumbar Fascia"],
    biomechanicsCue: "Lie prone with hips anchored to mat. Press through palms, lifting chest while depressing shoulders away from ears.",
    steps: [
      "Lie face down on mat with palms under shoulders.",
      "Keep pelvis and tops of feet firmly pressed into floor.",
      "Press through hands to lift upper torso, extending spine.",
      "Hold for 30 seconds while breathing into abdominal wall.",
    ],
    commonMistakes: [
      "Lifting hips off floor.",
      "Compressing lumbar spine abruptly.",
    ],
    breathingPattern: "Inhale into abdominal wall → Exhale relaxing shoulders down.",
    diagramUrl: "/anatomy/cobra_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "QL Side Bend & Lateral Reach",
    normalizedName: "ql_side_bend_lateral_reach",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Quadratus Lumborum (QL)", "Internal & External Obliques"],
    secondaryMuscles: ["Latissimus Dorsi", "Intercostals", "Gluteus Medius"],
    biomechanicsCue: "Stand or sit tall. Reach one arm overhead and side-bend torso, anchoring opposite hip down to open deep lower back flank.",
    steps: [
      "Stand with feet shoulder-width or sit tall in chair.",
      "Raise right arm overhead and side-bend torso to the left.",
      "Reach right hand diagonally across while keeping right foot/hip anchored.",
      "Hold for 30-45 seconds per side.",
    ],
    commonMistakes: [
      "Twisting torso forward during side bend.",
      "Collapsing chest.",
    ],
    breathingPattern: "Inhale expanding lateral ribcage and flank → Exhale deepening side bend.",
    diagramUrl: "/anatomy/ql_stretch.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Supine Spinal Twist",
    normalizedName: "supine_spinal_twist",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Gluteus Medius", "Internal & External Obliques", "Erector Spinae"],
    secondaryMuscles: ["Pectoralis Major", "Piriformis", "Thoracolumbar Fascia"],
    biomechanicsCue: "Lie on back with arms in 'T'. Cross one knee across body toward floor, keeping both shoulder blades flat against mat.",
    steps: [
      "Lie on back with arms extended out to sides like a 'T'.",
      "Draw right knee into chest, then guide it across body to the left floor.",
      "Turn head to look over right shoulder while keeping right shoulder blade on mat.",
      "Hold for 45 seconds, then switch sides.",
    ],
    commonMistakes: [
      "Allowing stretching shoulder to lift completely off floor.",
      "Forcing knee down with excessive hand pressure.",
    ],
    breathingPattern: "Inhale lengthen spine → Exhale allowing knee and shoulder to melt into floor.",
    diagramUrl: "/anatomy/supine_twist.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "World's Greatest Stretch",
    normalizedName: "worlds_greatest_stretch",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Psoas Major", "Thoracic Spine Rotators", "Gluteus Medius"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Anterior Deltoid", "Pectoralis Major"],
    biomechanicsCue: "Deep runner's lunge. Drop inside elbow toward arch of front foot, then reach hand to ceiling in full thoracic rotation.",
    steps: [
      "Step left foot forward into deep lunge; place right hand on floor.",
      "Lower left elbow toward left inner ankle.",
      "Rotate torso left and reach left arm toward ceiling, tracking hand with eyes.",
      "Hold 2 seconds, return hand, and switch sides.",
    ],
    commonMistakes: [
      "Letting back knee collapse into floor.",
      "Rotating through lower back rather than thoracic spine.",
    ],
    breathingPattern: "Inhale on elbow dip → Exhale on overhead thoracic reach.",
    diagramUrl: "/anatomy/worlds_greatest.svg",
    diagramStatus: "PENDING_APPROVAL",
  },
];
