/**
 * Unified Exercise & Mobility Stretch Library with Complete Kinesiological Data
 * Unifies all resistance training exercises, static stretches, dynamic warmups, and foam roll movements
 * into a single coherent schema with verified target muscles and anatomy diagrams.
 */

export interface UnifiedExerciseItem {
  id?: string;
  name: string;
  normalizedName: string;
  type: "EXERCISE" | "STRETCH" | "MOBILITY" | "CARDIO" | "WELLNESS";
  muscleGroup: string;
  equipment: string;
  category: "STRENGTH" | "BODYWEIGHT" | "CARDIO" | "STATIC_STRETCH" | "DYNAMIC_WARMUP" | "FOAM_ROLL" | "WELLNESS";
  primaryMuscles: string[];
  secondaryMuscles: string[];
  biomechanicsCue: string;
  steps: string[];
  commonMistakes: string[];
  breathingPattern: string;
  diagramUrl: string;
  diagramStatus: "APPROVED" | "PENDING_APPROVAL" | "REJECTED" | "NEEDS_REVISION";
  diagramNotes?: string;
  approvedByUserId?: string | null;
  approvedAt?: string | null;
  isCustom?: boolean;
  createdByUserId?: string | null;
  createdByUserRole?: string;
}

export function normalizeExerciseName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");
}

export const INITIAL_UNIFIED_EXERCISES: UnifiedExerciseItem[] = [
  // ==========================================
  // CHEST & PUSH EXERCISES
  // ==========================================
  {
    name: "Barbell Bench Press",
    normalizedName: "barbell_bench_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major (Sternal & Clavicular Heads)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii (Lateral/Medial Heads)", "Serratus Anterior"],
    biomechanicsCue: "Retract and depress scapulae, drive feet into the floor, flare lats, and touch lower sternum under control.",
    steps: [
      "Set Up: Lie flat on bench with eyes directly under the racked bar. Plant feet flat on floor.",
      "Grip: Grip bar slightly wider than shoulder-width with wrists stacked over elbows.",
      "Descent: Unrack bar, pull shoulder blades together, and lower bar in a slight arc to the lower sternum/xiphoid process.",
      "Drive: Press bar up and slightly back toward eye line while squeezing chest and locking elbows at top.",
    ],
    commonMistakes: [
      "Flaring elbows out at 90° (places high shear stress on anterior shoulder capsule).",
      "Bouncing the bar off the ribcage.",
      "Lifting hips off the bench during heavy drive.",
    ],
    breathingPattern: "Inhale deeply at the top to create intra-abdominal pressure → Lower bar with held breath → Exhale forcefully past the sticking point.",
    diagramUrl: "/anatomy/bench.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Incline Barbell Bench Press",
    normalizedName: "incline_barbell_bench_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major (Clavicular 'Upper' Head)"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii", "Serratus Anterior"],
    biomechanicsCue: "Set bench to 30-45°. Lower bar to upper clavicular notch without flaring elbows.",
    steps: [
      "Set Up: Position bench at 30° to 45° angle. Plant heels firmly on floor.",
      "Unrack: Retract scapulae and press bar to full arm extension above upper chest.",
      "Eccentric: Lower smoothly to upper chest / clavicle area.",
      "Concentric: Drive upward without rounding shoulders forward.",
    ],
    commonMistakes: [
      "Bench angle too steep (>45° turns it into an anterior delt press).",
      "Excessive arching that turns incline into a flat press.",
    ],
    breathingPattern: "Inhale on descent → Exhale as bar passes sticking point.",
    diagramUrl: "/anatomy/bench.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Flat Dumbbell Press",
    normalizedName: "flat_dumbbell_press",
    type: "EXERCISE",
    muscleGroup: "Chest",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Anterior Deltoid", "Triceps Brachii", "Coracobrachialis"],
    biomechanicsCue: "Allows natural converging pressing arc and deeper stretch without fixed barbell constraints.",
    steps: [
      "Set Up: Kick dumbbells up to shoulders as you lie back onto flat bench.",
      "Descent: Lower dumbbells with 45° elbow tuck until thumbs graze outer chest.",
      "Press: Drive up and slightly inward in an arc, squeezing pecs at the apex.",
    ],
    commonMistakes: [
      "Clanging dumbbells together at top (removes muscle tension).",
      "Wrists collapsing backward.",
    ],
    breathingPattern: "Inhale down into deep chest stretch → Exhale as you press up.",
    diagramUrl: "/anatomy/bench.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Push-Up",
    normalizedName: "push_up",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoid", "Rectus Abdominis", "Serratus Anterior"],
    biomechanicsCue: "Rigid plank line from crown of head to heels. Tuck elbows 45° like an arrow, not a 'T'.",
    steps: [
      "Start in high plank with hands slightly wider than shoulder width.",
      "Lower chest until 1 inch off floor while keeping glutes and core braced.",
      "Press floor away until elbows fully lock out with protraction at the top.",
    ],
    commonMistakes: [
      "Sagging lumbar spine / drooping hips.",
      "Head jutting forward to fake depth.",
    ],
    breathingPattern: "Inhale on lowering → Exhale as you push up.",
    diagramUrl: "/anatomy/bench.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Chest Dip",
    normalizedName: "chest_dip",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Lower Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoid", "Latissimus Dorsi", "Rhomboids"],
    biomechanicsCue: "Lean torso 30° forward, flare elbows slightly out, and lower until shoulders pass elbows.",
    steps: [
      "Mount parallel dip bars and lock elbows.",
      "Lean upper torso forward with chin tucked.",
      "Lower body under control to a 90° elbow angle.",
      "Press back up to lockout while maintaining forward forward torso tilt.",
    ],
    commonMistakes: [
      "Staying completely upright (shifts focus to triceps).",
      "Dropping too fast into shoulder joint hyperextension.",
    ],
    breathingPattern: "Inhale on descent → Exhale on pressing up.",
    diagramUrl: "/anatomy/dips.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // BACK & PULL EXERCISES
  // ==========================================
  {
    name: "Barbell Deadlift",
    normalizedName: "barbell_deadlift",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Gluteus Maximus", "Hamstrings (Biceps Femoris, Semitendinosus)", "Erector Spinae"],
    secondaryMuscles: ["Latissimus Dorsi", "Trapezius (Upper/Middle)", "Quadriceps", "Forearms (Grip)"],
    biomechanicsCue: "Wedge hips down into the bar, pull slack out with a metallic 'click', and push the floor away like a leg press.",
    steps: [
      "Set Up: Bar over mid-foot (1 inch from shins). Feet hip-width apart.",
      "Grip: Hinge at hips and grip bar just outside knees.",
      "Wedge: Pull chest proud, engage lats, drop hips until shins touch the bar.",
      "Drive: Push floor away through mid-foot, driving hips forward into lockout.",
    ],
    commonMistakes: [
      "Rounding lumbar spine under heavy load.",
      "Yanking the bar abruptly without pulling slack first.",
      "Hyperextending lower back at lockout.",
    ],
    breathingPattern: "Big diaphragmatic inhale into belt at bottom → Hold breath during lift → Exhale at lockout.",
    diagramUrl: "/anatomy/deadlift.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Barbell Bent-Over Row",
    normalizedName: "barbell_bent_over_row",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle & Lower Trapezius"],
    secondaryMuscles: ["Posterior Deltoid", "Biceps Brachii", "Brachialis", "Erector Spinae"],
    biomechanicsCue: "Hinge torso to 45°, pull elbows toward hips/navel, and squeeze shoulder blades together.",
    steps: [
      "Hinge hips back with knees soft until torso is at 45° angle.",
      "Pull bar into lower ribcage/navel by driving elbows back.",
      "Squeeze rhomboids and lats for 1 second at top.",
      "Lower bar slowly with full lat stretch at bottom.",
    ],
    commonMistakes: [
      "Using excessive torso jerk to bounce the bar.",
      "Pulling to clavicle instead of navel.",
    ],
    breathingPattern: "Inhale at bottom stretch → Exhale as you pull bar to torso.",
    diagramUrl: "/anatomy/barbell_row.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Lat Pulldown (Wide Grip)",
    normalizedName: "lat_pulldown_wide_grip",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Latissimus Dorsi (Outer Flare)"],
    secondaryMuscles: ["Teres Major", "Biceps Brachii", "Brachioradialis", "Lower Trapezius"],
    biomechanicsCue: "Lean back 10-15°, drive elbows straight down into back pockets, and lead with proud chest.",
    steps: [
      "Grip bar with overhand grip 1.5x shoulder width.",
      "Secure thighs under thigh pad.",
      "Depress scapulae and pull bar down to upper clavicle.",
      "Resist the cable smoothly back to full overhead stretch.",
    ],
    commonMistakes: [
      "Leaning back 45° turning pulldown into a sloppy row.",
      "Pulling bar behind the neck.",
    ],
    breathingPattern: "Inhale at overhead stretch → Exhale as you pull to chest.",
    diagramUrl: "/anatomy/lat_pulldown.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Pull-Up",
    normalizedName: "pull_up",
    type: "EXERCISE",
    muscleGroup: "Bodyweight",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Biceps Brachii", "Rhomboids", "Lower Trapezius", "Core"],
    biomechanicsCue: "Full dead hang to chin over bar. Initiate by depressing scapulae before bending elbows.",
    steps: [
      "Hang from overhead bar with pronated grip wider than shoulders.",
      "Set shoulder blades down and back.",
      "Pull chest to bar until chin clears bar height.",
      "Lower with controlled 3-second descent back to dead hang.",
    ],
    commonMistakes: [
      "Kipping or swinging legs.",
      "Cutting range of motion at bottom or top.",
    ],
    breathingPattern: "Inhale at bottom hang → Exhale as you pull chin over bar.",
    diagramUrl: "/anatomy/lat_pulldown.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Face Pull",
    normalizedName: "face_pull",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Posterior Deltoids", "Infraspinatus", "Teres Minor"],
    secondaryMuscles: ["Middle/Lower Trapezius", "Rhomboids"],
    biomechanicsCue: "Set cable at eye level. Pull center of rope to bridge of nose while externally rotating thumbs back.",
    steps: [
      "Attach rope to eye-level cable with overhand/neutral thumbs-back grip.",
      "Step back for tension, pull rope toward forehead while separating hands outward.",
      "Hold external rotation squeeze for 1 second.",
      "Control cable back to straight arm stretch.",
    ],
    commonMistakes: [
      "Pulling downward to neck instead of outward to forehead.",
      "Using heavy momentum and hyperextending lower back.",
    ],
    breathingPattern: "Inhale at reach → Exhale as hands pull back to ears.",
    diagramUrl: "/anatomy/face_pull.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // LEGS & LOWER BODY
  // ==========================================
  {
    name: "Barbell Back Squat",
    normalizedName: "barbell_back_squat",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps Femoris (Vastus Lateralis, Medialis, Intermedius, Rectus Femoris)", "Gluteus Maximus"],
    secondaryMuscles: ["Adductor Magnus", "Hamstrings", "Erector Spinae", "Transverse Abdominis"],
    biomechanicsCue: "Break at hips and knees simultaneously. Spread the floor with feet, driving knees out in line with toes.",
    steps: [
      "Bar positioned across upper traps. Unrack and take 3 deliberate setup steps.",
      "Brace core 360°, descend until hip crease is below top of knees (parallel).",
      "Drive out of the hole by pressing through full foot, maintaining proud chest.",
    ],
    commonMistakes: [
      "Knees caving inward (valgus collapse).",
      "Heels lifting off floor.",
      "Good-morning squat where hips shoot up before torso.",
    ],
    breathingPattern: "Deep diaphragmatic inhale and 360° brace at top → Hold down → Exhale past sticking point.",
    diagramUrl: "/anatomy/squat.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Bulgarian Split Squat",
    normalizedName: "bulgarian_split_squat",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Gluteus Medius", "Hamstrings", "Adductors", "Soleus"],
    biomechanicsCue: "Elevate rear foot on bench. Drop back knee toward floor while keeping 85% of weight on front heel/midfoot.",
    steps: [
      "Stand 2-3 feet in front of bench. Place top of rear foot flat on bench pad.",
      "Hold dumbbells at sides with tall spine and slight forward torso lean.",
      "Lower rear knee straight down until hovering 1 inch above floor.",
      "Drive through front mid-foot to stand back up.",
    ],
    commonMistakes: [
      "Stance too short causing extreme knee shear.",
      "Front heel lifting off floor.",
    ],
    breathingPattern: "Inhale down into deep lunge → Exhale as front leg presses up.",
    diagramUrl: "/anatomy/bulgarian_split_squat.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Leg Extension",
    normalizedName: "leg_extension",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Quadriceps Femoris (Rectus Femoris, Vastus Lateralis, Vastus Medialis)"],
    secondaryMuscles: ["Tensor Fasciae Latae", "Anterior Tibialis"],
    biomechanicsCue: "Align machine pivot axis with knee joint. Extend knees fully and hold 1 second at peak lockout.",
    steps: [
      "Adjust back pad so knees bend over seat edge; pad rests against lower tibia.",
      "Grip side handles firmly to glue pelvis into seat.",
      "Extend knees smoothly to full horizontal lockout.",
      "Lower under strict 3-second control without letting plates touch.",
    ],
    commonMistakes: [
      "Lifting hips off seat using momentum.",
      "Pivot axis not aligned with knee joint.",
    ],
    breathingPattern: "Inhale at bottom → Exhale as legs extend to top.",
    diagramUrl: "/anatomy/leg_extension.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Leg Curl",
    normalizedName: "leg_curl",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus)"],
    secondaryMuscles: ["Gastrocnemius (Calf)", "Gracilis", "Sartorius"],
    biomechanicsCue: "Keep hips pressed down into pad. Flex knees smoothly and squeeze heels to glutes.",
    steps: [
      "Position knee joint in line with machine pivot. Pad rests above Achilles.",
      "Curl heels up toward glutes in a smooth arc.",
      "Squeeze hamstrings tightly for 1 count at peak flexion.",
      "Resist back over 3 seconds to near full extension.",
    ],
    commonMistakes: [
      "Arching lower back and lifting hips to heave weight.",
      "Letting weight plates slam.",
    ],
    breathingPattern: "Inhale on extension stretch → Exhale as you curl heels to glutes.",
    diagramUrl: "/anatomy/leg_curl.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Barbell Hip Thrust",
    normalizedName: "barbell_hip_thrust",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings", "Quadriceps", "Adductor Magnus", "Erector Spinae"],
    biomechanicsCue: "Upper back on bench, barbell across hip crease with pad. Drive through heels and tuck pelvis at top (posterior pelvic tilt).",
    steps: [
      "Sit on floor with upper back against bench pad; roll padded barbell over hips.",
      "Plant feet shoulder-width, shins vertical at top of thrust.",
      "Drive hips straight up by contracting glutes until thighs and torso form a flat table.",
      "Tuck chin and look forward, holding peak glute squeeze for 1 full second.",
      "Lower under control to starting hover.",
    ],
    commonMistakes: [
      "Hyperextending lumbar spine instead of posterior pelvic tilt.",
      "Looking up at ceiling instead of maintaining forward eye line.",
      "Feet too far out (shifts tension to hamstrings) or too close (shifts to quads).",
    ],
    breathingPattern: "Inhale at bottom → Exhale forcefully as you drive hips up to lockout.",
    diagramUrl: "/anatomy/hip_thrust.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Standing Calf Raise",
    normalizedName: "standing_calf_raise",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Gastrocnemius (Medial & Lateral Heads)", "Soleus"],
    secondaryMuscles: ["Achilles Tendon", "Tibialis Posterior", "Peroneals"],
    biomechanicsCue: "Lower heels deep below platform for 2-second stretch, then drive straight up through the big toe ball.",
    steps: [
      "Place balls of feet on platform with heels hanging over edge.",
      "Lower heels into deep dorsiflexion stretch; hold 1 full second.",
      "Drive up onto balls of feet as high as possible.",
      "Squeeze calves at apex without rolling ankles outward.",
    ],
    commonMistakes: [
      "Bouncing fast using Achilles elastic rebound.",
      "Rolling onto outer pinky toes.",
    ],
    breathingPattern: "Inhale on deep descent → Exhale as you drive onto toes.",
    diagramUrl: "/anatomy/calf_raise.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hip Abduction Machine",
    normalizedName: "hip_abduction_machine",
    type: "EXERCISE",
    muscleGroup: "Legs",
    equipment: "Machine",
    category: "STRENGTH",
    primaryMuscles: ["Gluteus Medius", "Gluteus Minimus", "Tensor Fasciae Latae"],
    secondaryMuscles: ["Upper Gluteus Maximus", "Piriformis", "Deep Hip Rotators"],
    biomechanicsCue: "Sit tall or slight forward hinge. Drive outward against the pads with the lateral edges of knees.",
    steps: [
      "Sit upright with outer knees firmly against abduction pads.",
      "Drive knees outward in a wide arc until full gluteus medius contraction.",
      "Hold outer spread position for 1 second.",
      "Resist inward return under 3-second control.",
    ],
    commonMistakes: [
      "Using torso swinging to bounce pads outward.",
      "Feet leading push instead of knees.",
    ],
    breathingPattern: "Inhale at center → Exhale as you spread knees outward.",
    diagramUrl: "/anatomy/hip_abduction.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // SHOULDERS & ARMS
  // ==========================================
  {
    name: "Overhead Barbell Press (OHP)",
    normalizedName: "overhead_barbell_press",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Anterior Deltoid", "Lateral Deltoid"],
    secondaryMuscles: ["Triceps Brachii", "Serratus Anterior", "Upper Pectoralis Major", "Upper Trapezius"],
    biomechanicsCue: "Clench glutes and brace core. Press bar in vertical path, moving head back to clear chin, then pushing head through 'the window' at top.",
    steps: [
      "Grip bar just outside shoulders with elbows tucked forward.",
      "Brace glutes and abs, press bar straight up past nose.",
      "As bar clears forehead, bring head forward to lock out directly over spine.",
      "Lower with control back to collarbone rest.",
    ],
    commonMistakes: [
      "Excessive lumbar hyperextension / leaning back.",
      "Pressing bar out in front instead of straight over center of gravity.",
    ],
    breathingPattern: "Deep diaphragmatic inhale at bottom → Exhale past eye level.",
    diagramUrl: "/anatomy/press.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Standing Dumbbell Lateral Raise",
    normalizedName: "standing_dumbbell_lateral_raise",
    type: "EXERCISE",
    muscleGroup: "Shoulders",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Lateral Deltoid"],
    secondaryMuscles: ["Anterior Deltoid", "Posterior Deltoid", "Supraspinatus", "Upper Trapezius"],
    biomechanicsCue: "Raise in the scapular plane (30° forward). Lead with elbows, pouring water slightly with pinkies high.",
    steps: [
      "Stand with dumbbells at sides, slight 10° forward torso hinge.",
      "Raise arms out and slightly forward in scapular plane to shoulder height.",
      "Hold peak contraction for 1 count.",
      "Lower dumbbells smoothly over 2.5 seconds.",
    ],
    commonMistakes: [
      "Shrugging traps up to ears.",
      "Swinging hips to generate momentum.",
    ],
    breathingPattern: "Inhale at bottom → Exhale as arms sweep up to shoulder level.",
    diagramUrl: "/anatomy/lateral_raise.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Barbell Bicep Curl",
    normalizedName: "barbell_bicep_curl",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Barbell",
    category: "STRENGTH",
    primaryMuscles: ["Biceps Brachii (Short & Long Heads)"],
    secondaryMuscles: ["Brachialis", "Brachioradialis", "Pronator Teres"],
    biomechanicsCue: "Pin elbows against ribcage. Curl bar up in smooth arc without swinging torso.",
    steps: [
      "Stand tall gripping barbell with underhand shoulder-width grip.",
      "Keep elbows pinned to sides, curl bar up toward upper chest.",
      "Squeeze biceps maximally for 1 second at apex.",
      "Lower under 3-second control to full elbow extension.",
    ],
    commonMistakes: [
      "Swinging lower back to heave weight.",
      "Letting elbows drift forward (takes tension off biceps).",
    ],
    breathingPattern: "Inhale on descent → Exhale as bar curls upward.",
    diagramUrl: "/anatomy/bicep_curl.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Dumbbell Hammer Curl",
    normalizedName: "dumbbell_hammer_curl",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Dumbbell",
    category: "STRENGTH",
    primaryMuscles: ["Brachialis", "Brachioradialis", "Biceps Brachii (Long Head)"],
    secondaryMuscles: ["Wrist Flexors & Extensors"],
    biomechanicsCue: "Neutral thumbs-up grip. Squeeze forearms and brachialis at the top.",
    steps: [
      "Hold dumbbells with palms facing each other (neutral grip).",
      "Curl dumbbells up toward shoulders while keeping palms facing inward.",
      "Squeeze peak contraction at top.",
      "Lower slowly to full arm hang.",
    ],
    commonMistakes: [
      "Rotating wrists into supination (keep neutral throughout).",
      "Using body momentum.",
    ],
    breathingPattern: "Inhale at bottom → Exhale as dumbbells curl up.",
    diagramUrl: "/anatomy/hammer_curl.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Tricep Rope Pushdown",
    normalizedName: "tricep_rope_pushdown",
    type: "EXERCISE",
    muscleGroup: "Arms",
    equipment: "Cable",
    category: "STRENGTH",
    primaryMuscles: ["Triceps Brachii (Lateral & Medial Heads)"],
    secondaryMuscles: ["Triceps Brachii (Long Head)", "Anconeus"],
    biomechanicsCue: "Pin elbows at sides. Push down and flare rope ends outward at bottom lockout.",
    steps: [
      "Attach rope to high pulley; grip with neutral thumbs-up hold.",
      "Keep elbows locked at sides, push rope down until arms are straight.",
      "Spread rope ends apart at bottom for peak tricep contraction.",
      "Allow forearms to rise back to 90° under cable tension.",
    ],
    commonMistakes: [
      "Elbows flaring and moving forward and back.",
      "Hunching shoulders over the rope.",
    ],
    breathingPattern: "Inhale as hands rise → Exhale forcefully on downward extension.",
    diagramUrl: "/anatomy/tricep_pushdown.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // CORE & POSTURE
  // ==========================================
  {
    name: "Plank",
    normalizedName: "plank",
    type: "EXERCISE",
    muscleGroup: "Core",
    equipment: "Bodyweight",
    category: "BODYWEIGHT",
    primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis", "Internal & External Obliques"],
    secondaryMuscles: ["Gluteus Maximus", "Serratus Anterior", "Quadriceps"],
    biomechanicsCue: "Form a straight board from head to heels. Squeeze glutes and pull belly button to spine.",
    steps: [
      "Rest forearms on floor with elbows directly under shoulders.",
      "Extend legs back on toes, squeezing quads, glutes, and abs.",
      "Hold rigid bridge without letting hips sag or pike.",
    ],
    commonMistakes: [
      "Sagging lower back (lumbar extension).",
      "Holding breath (maintain steady diaphragmatic breathing).",
    ],
    breathingPattern: "Steady rhythmic nose inhalations and pursed lip exhalations while maintaining 360° abdominal brace.",
    diagramUrl: "/anatomy/plank.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hyperextensions (Back Extension)",
    normalizedName: "hyperextensions_back_extension",
    type: "EXERCISE",
    muscleGroup: "Back",
    equipment: "Bodyweight",
    category: "STRENGTH",
    primaryMuscles: ["Erector Spinae (Spinalis, Longissimus, Iliocostalis)", "Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus)", "Quadratus Lumborum"],
    biomechanicsCue: "Hinge at hips over the 45° roman chair pad. Extend spine smoothly to neutral alignment without hyperextending neck.",
    steps: [
      "Position thighs against pad with pelvis slightly clear of front edge.",
      "Cross arms over chest or hold plate; hinge forward at hips until 90° bend.",
      "Engage glutes and lower back to raise torso in line with legs.",
      "Squeeze glutes and erectors for 1 full second at parallel.",
    ],
    commonMistakes: [
      "Aggressively arching lower back past neutral.",
      "Jerking head backward.",
    ],
    breathingPattern: "Inhale on descent → Exhale as you extend spine to neutral.",
    diagramUrl: "/anatomy/back_hyperextension.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },

  // ==========================================
  // MOBILITY & STRETCHES (STORED UNIFIED WITH EXERCISES)
  // ==========================================
  {
    name: "Pigeon Stretch",
    normalizedName: "pigeon_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Piriformis", "Deep Hip External Rotators", "Gluteus Medius"],
    secondaryMuscles: ["Gluteus Maximus", "Psoas Major", "Iliacus (Rear Leg Hip Flexor)", "Tensor Fasciae Latae"],
    biomechanicsCue: "Front shin at 45-90° across mat. Square both hip bones to the floor, breathing deeply into the outer hip capsule.",
    steps: [
      "From quadruped or downward dog, bring right knee forward behind right wrist.",
      "Angle right foot across toward left hand, extending left leg straight back.",
      "Square hips toward the floor and lower torso forward over front shin.",
      "Hold for 45-60 seconds per side while taking deep belly breaths.",
    ],
    commonMistakes: [
      "Rolling onto outer hip of front leg (keeps hips from squaring).",
      "Torquing front knee (keep front ankle flexed to protect joint).",
    ],
    breathingPattern: "4-second deep nasal inhale → 6-second relaxing exhale, melting deeper into the hip capsule.",
    diagramUrl: "/anatomy/pigeon.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Chest Doorway Stretch",
    normalizedName: "chest_doorway_stretch",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Pectoralis Major", "Pectoralis Minor"],
    secondaryMuscles: ["Anterior Deltoid", "Coracobrachialis", "Biceps Brachii (Short Head)"],
    biomechanicsCue: "Forearm flush against door frame at 90°. Step forward with same-side foot, turning torso away until deep chest stretch is felt.",
    steps: [
      "Stand in doorway; place forearm flat against door jamb with elbow bent 90°.",
      "Step forward with same side foot.",
      "Gently rotate torso away from door frame until chest and shoulder open up.",
      "Hold for 30-45 seconds, then repeat on opposite side.",
    ],
    commonMistakes: [
      "Shrugging shoulder up toward ear (keep scapula depressed).",
      "Arching lower back instead of opening chest.",
    ],
    breathingPattern: "Inhale tall through spine → Exhale as chest relaxes deeper into doorway stretch.",
    diagramUrl: "/anatomy/chest_stretch.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Cat-Cow Spine Mobility",
    normalizedName: "cat_cow_spine_mobility",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Erector Spinae", "Rectus Abdominis", "Thoracolumbar Fascia"],
    secondaryMuscles: ["Serratus Anterior", "Rhomboids", "Neck Extensors & Flexors"],
    biomechanicsCue: "Sync movement with breath. Cow: inhale, drop belly, look up. Cat: exhale, round spine, push floor away.",
    steps: [
      "Start on all fours with hands under shoulders, knees under hips.",
      "Cow: Inhale, arch back, drop belly, lift tailbone and gaze upward.",
      "Cat: Exhale, tuck tailbone, round spine to ceiling, tuck chin to chest.",
      "Flow continuously through 8-10 cycles smoothly.",
    ],
    commonMistakes: [
      "Bending elbows instead of moving spine.",
      "Rushing repetitions without breath synchronization.",
    ],
    breathingPattern: "Inhale on Cow (extension) → Exhale forcefully on Cat (flexion).",
    diagramUrl: "/anatomy/cat_cow.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Hamstring Standing Fold",
    normalizedName: "hamstring_standing_fold",
    type: "STRETCH",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "STATIC_STRETCH",
    primaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus)"],
    secondaryMuscles: ["Gastrocnemius", "Erector Spinae", "Gluteus Maximus"],
    biomechanicsCue: "Hinge at hips with soft knees. Let head hang heavy, reaching chest toward shins.",
    steps: [
      "Stand tall with feet hip-width apart.",
      "Hinge at hips, folding upper body over thighs.",
      "Let head and arms hang freely toward the floor.",
      "Hold for 45 seconds, relaxing deeper on each exhale.",
    ],
    commonMistakes: [
      "Locking knees backward into hyperextension.",
      "Straining neck by looking forward.",
    ],
    breathingPattern: "Inhale to lengthen spine → Exhale to fold deeper toward thighs.",
    diagramUrl: "/anatomy/pigeon.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "World's Greatest Stretch",
    normalizedName: "worlds_greatest_stretch",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "DYNAMIC_WARMUP",
    primaryMuscles: ["Psoas Major", "Thoracic Spine Rotators", "Gluteus Medius"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Anterior Deltoid", "Pectoralis Major"],
    biomechanicsCue: "Deep runner's lunge. Drop inside elbow toward arch of front foot, then reach hand to ceiling in full thoracic rotation.",
    steps: [
      "Step left foot forward into deep lunge; place right hand on floor.",
      "Lower left elbow toward left inner ankle.",
      "Rotate torso left and reach left arm toward ceiling, tracking hand with eyes.",
      "Hold 2 seconds, return hand, and switch sides.",
    ],
    commonMistakes: [
      "Letting back knee collapse into floor.",
      "Rotating through lower back rather than thoracic spine.",
    ],
    breathingPattern: "Inhale on elbow dip → Exhale on overhead thoracic reach.",
    diagramUrl: "/anatomy/cat_cow.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
  {
    name: "Foam Roll Upper Back (Thoracic Spine)",
    normalizedName: "foam_roll_upper_back",
    type: "MOBILITY",
    muscleGroup: "Stretching",
    equipment: "Bodyweight",
    category: "FOAM_ROLL",
    primaryMuscles: ["Thoracic Spine Extensors", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Latissimus Dorsi", "Posterior Deltoid"],
    biomechanicsCue: "Foam roller across mid-back. Support head with hands, hug elbows together to expose rhomboids, and roll smoothly from mid-back to top of shoulders.",
    steps: [
      "Lie with foam roller across middle back below shoulder blades.",
      "Support head with hands, lift hips slightly off floor.",
      "Roll slowly back and forth over upper back for 60 seconds.",
      "Pause on tight spots and extend upper back over roller for 3 breaths.",
    ],
    commonMistakes: [
      "Rolling onto lower lumbar spine (keep roller above bottom rib).",
      "Pulling neck with hands.",
    ],
    breathingPattern: "Slow, rhythmic deep breathing throughout rolling.",
    diagramUrl: "/anatomy/cat_cow.jpg",
    diagramStatus: "PENDING_APPROVAL",
  },
];
